name: Publish PDF Resume

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  publish_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: docker://venura9/pandoc
        with:
          args: >-
            pandoc
            -V papersize=a4
            -V margin-top=1cm
            -V margin-left=1cm
            -V margin-right=1cm
            -V margin-bottom=1cm
            -f gfm
            -t html5
            --metadata pagetitle="Venura Athukorala"
            --output=personal_resume.pdf
            resume_header.md experience.md certifications.md education.md

      - uses: docker://venura9/pandoc
        with:
          args: >-
            pandoc
            -V papersize=a4
            -V margin-top=1cm
            -V margin-left=1cm
            -V margin-right=1cm
            -V margin-bottom=1cm
            -f gfm
            -t html5
            --metadata pagetitle="Venura Athukorala"
            --output=work_resume.pdf
            work_resume_header.md work_resume_experience.md certifications.md education.md
          
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: ./*.pdf
