name: Publish PDF Resume

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  publish_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: docker://pandoc/latex:2.9
        with:
          args: >-
            --pdf-engine=xelatex
            --output=resume.pdf
            -V documentclass=scrarticle
            -V geometry:a4paper
            -V geometry:margin=2cm
            -V geometry:nohead
            resume_header.md experience.md certifications.md education.md

      - uses: docker://pandoc/latex:2.9
        with:
          args: >-
            --pdf-engine=xelatex
            --output=work_resume.pdf
            -V documentclass=scrarticle
            -V geometry:a4paper
            -V geometry:margin=2cm
            -V geometry:nohead
            work_header.md experience.md certifications.md education.md
          
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: ./*.pdf
